# Generated by Django 4.2.18 on 2025-02-09 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_managment', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='reason',
        ),
        migrations.AddField(
            model_name='payment',
            name='appointment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='patient_managment.appointment'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
