# Generated by Django 4.2.18 on 2025-02-09 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_managment', '0003_remove_payment_reason_payment_appointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_managment.appointment'),
        ),
    ]
