# Generated by Django 4.2.18 on 2025-02-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_managment', '0004_alter_payment_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
