# Generated by Django 4.2.18 on 2025-02-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_managment', '0009_alter_appointment_doctor_alter_appointment_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
