# Generated by Django 4.2.18 on 2025-02-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_managment', '0011_appointment_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
