# Generated by Django 4.2.18 on 2025-02-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_managment', '0012_appointment_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='count',
        ),
        migrations.AddField(
            model_name='doctor',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
